title:        Lucid
tagline:      'Lucid, a Jekyll theme'
version:      '0.1.2'
description:  'A simple, framework-free and content first <a href="http://jekyllrb.com/">jekyll</a> theme made by <a href="http://twitter.com/aebsr">@aebsr</a>'
# Omit trailing slashes from your site url
url:          http://aeb.sr/lucid-jekyll-theme
author:
  name:       'Antoine Butler'
  bio:        'A designer, developer and musician. His opinions are his own, and often offend.'
  email:      'antoinebsr@gmail.com'
  # Twitter user name WITH @ sign
  twitter:    '@aebsr'
  google_verify:     'm2QfwtTj5--Xr9RzyJf8JHdD5SkfKnjVTd2vhRo7CxQ'
  google_plus:       'AntoineButlerSr'
analytics:    'UA-34982219-1'
permalink:    pretty
pygments:     true
markdown:     kramdown
paginate:     4

links:
  - title: Theme Setup
    url: /theme-setup
  - title: Fork Me
    url: https://github.com/aebsr/lucid-jekyll-theme
    external: true
